# Constructs lower triangle of adjacency matrix for graphs generated by PaRMAT.

import sys

datafile = sys.argv[1]
nodes = {}

with open(datafile) as f:
    for line in f:
        entry = line.split()
        src_node, dst_node = entry[0], entry[1]

        if src_node not in nodes:
            nodes[src_node] = []
        if dst_node not in nodes:
            nodes[dst_node] = []

        nodes[src_node].append(dst_node)
        nodes[dst_node].append(src_node)

with open(datafile) as f:
    for node, neighbors in sorted(nodes.items()):
        for neighbor in neighbors:
            f.write(f"{node}\t{neighbor}\n")
